package javaplatform;

public class Jdk {
	
//JDK , PLATFORM DEPENDENT
//JRE , PLATFORM DEPENDENT
//JVM , PLATFORM DEPENDENT**
//COMPILER , PLATFORM DEPENDENT
//JIT compiler , PLATFORM DEPENDENT
//INTERPRETER , PLATFORM DEPENDENT
//BYTE CODE(.class file) , PLATFORM INDEPENDENT
//
}
